name: CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build and deploy
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
      FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
      GYM_INSTALLER_CERT_NAME: ${{ secrets.GYM_INSTALLER_CERT_NAME }}
      MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
      MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
    steps:
    - uses: actions/checkout@v2
    - name: Update fastlane
      run: bundle install
    - name: Deploy
      run: bundle exec fastlane beta
