name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: fastlane test
    - name: Export coverage
      run: |
        xcrun xccov view --report --json fastlane/test_output/FluxorExplorer.xcresult > cov.json
        git clone https://github.com/trax-retail/xccov2lcov.git
        cd xccov2lcov
        swift run xccov2lcov ../cov.json > ../coverage.lcov
    - name: Upload coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: 8746b86b307d2a4870981e9ad3e0210dac35d84210a300f3c6acb7193c2a36a5
      with:
        coverageCommand: ls
        coverageLocations: coverage.lcov:lcov
        debug: true
